changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: New Features
      labels:
        - Semver-Minor
        - enhancement
        - add-feature
        - new-feature
    - title: Bug fixed
      labels:
        - Semver-Patch
        - bug-fix
        - fix
        - patch
    - title: Improvements
      labels:
        - behaviour-change
    - title: Documentation
      labels:
        - docs
    - title: Translations
      labels:
        - i18n
        - add-language
        - update-translation
    - title: Config
      labels:
        - update-config
    - title: API changes
      labels:
        - refactoring
        
    - title: Breaking changes
      labels:
        - Semver-Major
        - breaking-change
    - title: Other changes
      labels:
        - "*"
